### PR TITLE
__cxa_demangle_gnu3: demangle 'z' as '...', not 'ellipsis'

### PR DESCRIPTION
**Pull request by emaste**
Obtained from ELF Tool Chain r3491

### CODE REVIEW

**Comment by cbergstrom** [comment]
Would it ever be possible to maintain attribution or leave the author's name in the commit message in the future. Thanks

**Comment by emaste** [comment]
Not sure I follow... I am the author.

If you think the "Obtained from" gives a different impression I could use "Obtained from ELF Tool Chain r3491 by Ed Maste."

**Comment by cbergstrom** [comment]
Is commit r3491 from you? If so nothing else, but there is an author field which can be used for commits which aren't authored by you. If that's inconvenient then simply putting the original author's name in the commit comment should be fine. Hope this clarifies

**Comment by emaste** [comment]
Yes r3491 is from me.

**Pull request merged**
